format = """
$time\
$username\
$directory\
"""
command_timeout = 5000
# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#434c5e"
style_root = "bg:#434c5e"
format = '[$user ]($style)'

[directory]
style = "bg:#4c566a"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[time]
style = "bg:#434c5e"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

